### PR TITLE
Add custom check if enter sticky mode function

### PR DESCRIPTION
**Pull request by Fykec**
May the user want enter the sticky mode base on other conditions

### CODE REVIEW

**Comment by jbutko** [comment]
Hi Fykec, thanks for your pull request. Can you please explain possible use cases for stickyModeFunction? Just to have an clearer idea about this pull request. Thanks.

**Comment by Fykec** [comment]
@jbutko

The user case is that:

there is a sticky navbar, **by default, you want hide it. not base on the position it's stay.** then when you scroll to the position that it stay. you  show it as fixed. So in this case navbar need a a possibility to customize when need to fix the navbar.

**Comment by jbutko** [comment]
Hi @Fykec, I tried to play with your pull request but to be honest I am still confused. I do not merge your pull request at the moment but thanks for your work though, really appreciate it.

**Comment by Fykec** [comment]
Ok。May My Request is not so common

**Pull request closed without merging**
